easy_admin:
        entities:
            # List the entity class name you want to manage
            - App\Entity\Article          
            - App\Entity\Client
            - App\Entity\Fournisseur
            - App\Entity\Achat
            - App\Entity\Vente
            - App\Entity\Stock